<a href="https://colab.research.google.com/github/Priyanka090319/CREDIT_CARD_FRAUD_DETECTION/blob/main/Credit%20card%20fraud%20detction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [7]:
credit_card_data = pd.read_csv('creditcard.csv')
credit_card_data.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0.0
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0.0
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0.0
3,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0.0
4,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0.0

In [8]:
credit_card_data.sample()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
270994,164362.0,2.102756,0.558445,-3.417242,0.489233,1.463357,-1.052806,0.638593,-0.244533,-0.035849,...,-0.06524,-0.067062,-0.107106,-0.005117,0.405262,0.697683,-0.093162,-0.030662,0.76,0.0

In [9]:
# dataset informations
credit_card_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 271287 entries, 0 to 271286
Data columns (total 31 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   Time    271287 non-null  float64
 1   V1      271287 non-null  float64
 2   V2      271287 non-null  float64
 3   V3      271287 non-null  float64
 4   V4      271287 non-null  float64
 5   V5      271287 non-null  float64
 6   V6      271287 non-null  float64
 7   V7      271287 non-null  float64
 8   V8      271287 non-null  float64
 9   V9      271286 non-null  float64
 10  V10     271286 non-null  float64
 11  V11     271286 non-null  float64
 12  V12     271286 non-null  float64
 13  V13     271286 non-null  float64
 14  V14     271286 non-null  float64
 15  V15     271286 non-null  float64
 16  V16     271286 non-null  float64
 17  V17     271286 non-null  float64
 18  V18     271286 non-null  float64
 19  V19     271286 non-null  float64
 20  V20     271286 non-null  float64
 21  V21     271286 non-null  float64
 22  V22     271286 non-null  float64
 23  V23     271286 non-null  float64
 24  V24     271286 non-null  float64
 25  V25     271286 non-null  float64
 26  V26     271286 non-null  float64
 27  V27     271286 non-null  float64
 28  V28     271286 non-null  float64
 29  Amount  271286 non-null  float64
 30  Class   271286 non-null  float64
dtypes: float64(31)
memory usage: 64.2 MB

In [10]:
# checking the number of missing values in each column
credit_card_data.isnull().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        1
V10       1
V11       1
V12       1
V13       1
V14       1
V15       1
V16       1
V17       1
V18       1
V19       1
V20       1
V21       1
V22       1
V23       1
V24       1
V25       1
V26       1
V27       1
V28       1
Amount    1
Class     1
dtype: int64

In [11]:
# distribution of legit transactions & fraudulent transactions
credit_card_data['Class'].value_counts()

Class
0.0    270805
1.0       481
Name: count, dtype: int64

In [12]:
legit = credit_card_data[credit_card_data.Class==0]
fraud = credit_card_data[credit_card_data['Class']==1]

In [13]:
fraud['Class']

541       1.0
623       1.0
4920      1.0
6108      1.0
6329      1.0
         ...
263080    1.0
263274    1.0
263324    1.0
263877    1.0
268375    1.0
Name: Class, Length: 481, dtype: float64

In [14]:
# statistical measures of the data
legit.Amount.describe()

count    270805.000000
mean         89.256037
std         247.420484
min           0.000000
25%           5.950000
50%          22.610000
75%          78.590000
max       19656.530000
Name: Amount, dtype: float64

In [15]:
fraud.Amount.describe()

count     481.000000
mean      121.239605
std       257.722080
min         0.000000
25%         1.000000
50%         8.640000
75%       104.810000
max      2125.870000
Name: Amount, dtype: float64

In [16]:

# compare the values for both transactions
credit_card_data.groupby('Class').mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0.0,91177.538506,0.000672,-0.019150,0.050389,-0.000074,-0.009064,0.009098,0.003286,-0.001187,0.004646,...,0.000542,-0.001493,-0.003805,-0.001714,0.000904,0.007281,0.000388,-0.000572,0.000389,89.256037
1.0,78754.848233,-4.843897,3.709169,-7.124813,4.604331,-3.241169,-1.403691,-5.660080,0.613744,-2.620426,...,0.370551,0.737419,0.004536,-0.051545,-0.110216,0.047133,0.049161,0.164155,0.074541,121.239605

In [17]:
legit_sample = legit.sample(n=492)

In [18]:
new_df = pd.concat([legit_sample,fraud],axis=0)

In [19]:
new_df

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
250980,155153.0,-0.107553,0.388638,1.350204,-0.101273,-0.070632,0.527327,-0.074537,0.318620,0.089007,...,0.323105,1.042789,-0.083153,0.761514,-0.824392,0.616868,0.182139,0.192477,11.49,0.0
151652,95919.0,-1.002792,0.439114,0.533086,-2.846269,1.109100,0.094450,1.926430,-0.300153,1.952976,...,-0.418658,-0.874421,-0.324601,-1.575281,1.286530,-1.239274,0.032480,-0.138818,151.58,0.0
183341,125757.0,0.178783,-0.065034,-0.083305,-1.408064,0.044600,-1.392901,0.360573,-0.334826,-0.951339,...,0.133727,0.330113,0.014602,0.037758,-0.698025,-0.343927,-0.007788,0.091822,15.00,0.0
50220,44396.0,1.004709,-1.352655,-0.288438,-1.051702,-0.372375,0.893920,-0.607529,0.192882,-0.822132,...,0.088492,-0.363142,-0.288692,-1.708022,0.281533,-0.315108,-0.015402,0.031547,231.37,0.0
71828,54459.0,-2.884332,0.241184,1.818326,0.315422,-1.202576,2.674072,-0.089243,0.822562,1.506324,...,0.008613,0.851010,-0.775485,-1.220964,0.557297,-0.271863,-1.566743,-0.994205,175.00,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
263080,160791.0,2.132386,0.705608,-3.530759,0.514779,1.527175,-1.716268,1.132791,-0.574214,0.128904,...,0.163739,0.703910,-0.245076,0.460049,0.920281,-0.216586,-0.026219,-0.025001,1.00,1.0
263274,160870.0,-0.644278,5.002352,-8.252739,7.756915,-0.216267,-2.751496,-3.358857,1.406268,-4.403852,...,0.587728,-0.605759,0.033746,-0.756170,-0.008172,0.532772,0.663970,0.192067,0.77,1.0
263324,160895.0,-0.848290,2.719882,-6.199070,3.044437,-3.301910,-1.992117,-3.734902,1.520079,-2.548788,...,1.125229,0.805258,0.199119,0.035206,0.012159,0.601658,0.137468,-0.171397,127.14,1.0
263877,161154.0,-3.387601,3.977881,-6.978585,1.657766,-1.100500,-3.599487,-3.686651,1.942252,-3.065089,...,1.043587,0.262189,-0.479224,-0.326638,-0.156939,0.113807,0.354124,0.287592,0.38,1.0
268375,163181.0,-5.238808,0.623013,-5.784507,1.678889,-0.364432,-0.477295,-4.276132,-0.695173,-2.971644,...,-0.326140,1.509239,-0.215966,-0.245727,0.893041,0.865758,0.854657,-0.964482,39.98,1.0

In [20]:
new_df['Class'].value_counts()

Class
0.0    492
1.0    481
Name: count, dtype: int64

In [21]:
new_df.groupby('Class').mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0.0,89485.731707,0.032707,-0.021505,0.165727,-0.036691,-0.055741,-0.202202,0.035879,0.042743,-0.034570,...,0.023030,0.008669,-0.042776,-0.032363,-0.019989,-0.001820,-0.016706,0.026517,0.023084,91.856626
1.0,78754.848233,-4.843897,3.709169,-7.124813,4.604331,-3.241169,-1.403691,-5.660080,0.613744,-2.620426,...,0.370551,0.737419,0.004536,-0.051545,-0.110216,0.047133,0.049161,0.164155,0.074541,121.239605

In [22]:
X = new_df.drop(columns='Class', axis=1)
Y = new_df['Class']

In [23]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, stratify=Y, random_state=2)

In [24]:
model=LogisticRegression()

In [25]:
# training the Logistic Regression Model with Training Data
model.fit(X_train, Y_train)
# accuracy on training data
X_train_prediction = model.predict(X_train)
training_data_accuracy = accuracy_score(X_train_prediction, Y_train)
print('Accuracy on Training data : ', training_data_accuracy)

Accuracy on Training data :  0.9473007712082262

/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

In [26]:
# accuracy on test data
X_test_prediction = model.predict(X_test)
test_data_accuracy = accuracy_score(X_test_prediction, Y_test)
print('Accuracy score on Test Data : ', test_data_accuracy)

Accuracy score on Test Data :  0.9384615384615385